# 需要的指标
- PPI 月（tushare）
- CPI 月 (tushare)
- GDP增速国内(tushare)、国外 季
- 长江有色报价  日 （爬虫）
- LME伦铝报价  日  （爬虫）
- M2 月  （tushare）
- 金属库存量  日 （爬虫）
- 期货价格（新增） 日

In [25]:
import pandas as pd
import tushare as ts
from datetime import date
pro = ts.pro_api('1bb24cb2558dd537628c80781f6bbabe77f3f7b84ff42f340dc641f8')

In [2]:
# Tushare获取数据+爬虫获取数据 
#     -> 存储到数据库中
#         -> 从数据库中取数据合并成为一个整体的数据
#             -> 数据对齐，清洗，缺失值填充，异常值删除

In [122]:
# 获取主力合约期货价格数据
# 查询铝对应的代码
# df = pro.fut_basic(exchange='SHFE', fut_type='1', fields='ts_code,symbol,name,list_date,delist_date')
main_heyue_map = pro.fut_mapping(ts_code='AL.SHF',start_date='20150101')
heyue_list = list(main_heyue_map['mapping_ts_code'].unique())
res = pro.fut_daily(ts_code=heyue_list[0],fields='ts_code,trade_date,close,settle,vol,amount,oi')
for ts_code in heyue_list:
    tmp = pro.fut_daily(ts_code=ts_code,fields='ts_code,trade_date,close,settle,vol,amount,oi')
    res = res.append(tmp) 

main_heyue_price_daily = pd.merge(main_heyue_map,res,how='inner',left_on=['trade_date','mapping_ts_code'],right_on=['trade_date','ts_code'])
main_heyue_price_daily = main_heyue_price_daily[['trade_date','ts_code_y','close','settle','vol','amount','oi']]
col=['trade_date','ts_code','close','settle','vol','amount','oi']
main_heyue_price_daily.columns = col
main_heyue_price_daily.to_csv('futures.csv',index=False)

In [14]:
# 获取PPI
ppi = pro.cn_ppi()
ppi.to_csv('PPI.csv')
# 获取CPI
cpi = pro.cn_cpi()
cpi.to_csv('CPI.csv')
# 获取GDP国内数据
gdp = pro.cn_gdp()
gdp.to_csv('GDP.csv')
# 获取M2指数
m2 = pro.cn_m()
m2.to_csv('M2.csv')

,month,ppi_yoy,ppi_mp_yoy,ppi_mp_qm_yoy,ppi_mp_rm_yoy,ppi_mp_p_yoy,ppi_cg_yoy,ppi_cg_f_yoy,ppi_cg_c_yoy,ppi_cg_adu_yoy,...,ppi_accu,ppi_mp_accu,ppi_mp_qm_accu,ppi_mp_rm_accu,ppi_mp_p_accu,ppi_cg_accu,ppi_cg_f_accu,ppi_cg_c_accu,ppi_cg_adu_accu,ppi_cg_dcg_accu
0,202101,0.3,0.5,1.0,-0.8,1.0,-0.2,1.6,-1.3,0.0,...,0.3,0.5,1.0,-0.8,1.0,-0.2,1.6,-1.3,0.0,-1.8
1,202012,-0.4,-0.5,-0.4,-1.6,0.0,-0.4,0.9,-1.8,-0.4,...,-1.8,-2.7,-5.2,-5.6,-1.3,0.5,2.9,-1.0,-0.3,-1.8
2,202011,-1.5,-1.8,-3.6,-4.2,-0.8,-0.8,0.1,-1.8,-0.5,...,-2.0,-2.9,-5.7,-5.9,-1.4,0.5,3.1,-1.0,-0.3,-1.8
3,202010,-2.1,-2.7,-5.1,-6.0,-1.2,-0.5,0.8,-1.7,-0.7,...,-2.0,-3.0,-5.9,-6.1,-1.5,0.7,3.4,-0.9,-0.3,-1.8
4,202009,-2.1,-2.8,-4.8,-6.2,-1.3,-0.1,2.1,-1.7,-0.8,...,-2.0,-3.0,-6.0,-6.1,-1.5,0.8,3.7,-0.8,-0.3,-1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,198212,-0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,198112,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,198012,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,197912,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,197812,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
futures_inventory_99_df = ak.futures_inventory_99(exchange=1, symbol=6, plot=True)
print(futures_inventory_99_df)

保存图片到本地: /Users/lizhe/个人桌面/实验室和研究生/中铝项目汇总/2021出差新指标预测/金属价格预测
           日期      库存     增减
0  2021-03-12  171794   8769
1  2021-03-05  163025  15067
2  2021-02-26  147958  35170
3  2021-02-19  112788  34217
4  2021-02-10   78571   9983
5  2021-02-05   68588   2023
6  2021-01-29   66565   -683
7  2021-01-22   67248  -6437
8  2021-01-15   73685  -8657
9  2021-01-08   82342  -4337

## 数据格式对齐过程
- PPI -> CDP  ->  M2  -> CPI

In [59]:
# 交易日历
# 结果：所有交易日的年月日数据

today = int(''.join(str(date.today()).split('-')))
calendar = pro.trade_cal(exchange='SHFE', start_date='20150101',end_date=today)
calendar['cal_month'] = calendar['cal_date'].apply(lambda x : int(str(x)[:-2]))
calendar = calendar[calendar['is_open'] == 1]
calendar = calendar[['cal_date','cal_month']]
# calendar

      cal_date  cal_month
4     20150105     201501
5     20150106     201501
6     20150107     201501
7     20150108     201501
8     20150109     201501
...        ...        ...
2268  20210318     202103
2269  20210319     202103
2272  20210322     202103
2273  20210323     202103
2274  20210324     202103

[1515 rows x 2 columns]

In [60]:
#  年季月 展开到  日 维度变换

#  PPI
# ppi_yoy   PPI：全部工业品：当月同比
# ppi_mom   PPI：全部工业品：环比
# ppi_accu  PPI：生产资料：累计同比
ppi = pd.read_csv('PPI.csv')
ppi = ppi[['month','ppi_yoy','ppi_mom','ppi_accu']]
ppi = ppi.dropna()
ppi = ppi[ppi.month >= 201501]


# CPI
cpi = pd.read_csv('CPI.csv')
cpi = cpi[['month','nt_val','town_val','cnt_val']]
cpi = cpi[cpi['month']>=201501]


# M2
m2 = pd.read_csv('M2.csv')
m2 = m2[['month','m0','m1','m2']]
m2 = m2[m2['month'] >= 201501]


# GDP

def quarter2month(quarter):
    year = quarter[0:4]
    last = quarter[4:]
    month = ''
    if(last == 'Q1'):
        month = year+'01,'+year+'02,'+year+'03'
    elif(last == 'Q2'):
        month = year+'04,'+year+'05,'+year+'06'
    elif(last == 'Q3'):
        month = year+'07,'+year+'08,'+year+'09'
    elif(last == 'Q4'):
        month = year+'10,'+year+'11,'+year+'12'
    return month
gdp = pd.read_csv('GDP.csv')
gdp = gdp[['quarter','gdp','pi','si','ti']]
gdp = gdp[gdp['quarter']>='2015Q1']
# gdp['month_tmp'] = gdp['quarter'].apply(lambda x : x[4:])
gdp['month'] = gdp['quarter'].apply(quarter2month)
gdp['month'] = gdp['month'].map(lambda x:x.split(','))
gdp = gdp.explode('month')
gdp['month'] = gdp['month'].apply(lambda x : int(x))

In [129]:
futures = pd.read_csv('futures.csv')
futures['trade_date'] = futures['trade_date'].apply(lambda x:int(x))
futures

,trade_date,ts_code,close,settle,vol,amount,oi
0,20210323,AL2105.SHF,17085.0,17160.0,628386.0,5393028.000,224586.0
1,20210323,AL2105.SHF,17085.0,17160.0,628386.0,5393028.000,224586.0
2,20210322,AL2105.SHF,17535.0,17535.0,335915.0,2945762.000,240775.0
3,20210322,AL2105.SHF,17535.0,17535.0,335915.0,2945762.000,240775.0
4,20210319,AL2105.SHF,17415.0,17410.0,318942.0,2776728.000,232436.0
...,...,...,...,...,...,...,...
1515,20150109,AL1503.SHF,12855.0,12845.0,62750.0,403152.405,161134.0
1516,20150108,AL1503.SHF,12805.0,12800.0,47172.0,301940.800,166856.0
1517,20150107,AL1503.SHF,12760.0,12790.0,63712.0,407487.330,168550.0
1518,20150106,AL1503.SHF,12845.0,12835.0,56276.0,361168.760,160562.0
1519,20150105,AL1503.SHF,12895.0,12915.0,56386.0,364185.645,157426.0

In [149]:
ppi_daily = pd.merge(calendar,ppi,how='left',left_on='cal_month',right_on='month')
cpi_daily = pd.merge(ppi_daily,cpi,how='left',left_on='month',right_on='month')
m2_daily = pd.merge(cpi_daily,m2,how='left',left_on='month',right_on='month')
gdp_daily = pd.merge(m2_daily,gdp,how='left',left_on='month',right_on='month')
# gdp_daily.describe()
# gdp_daily = gdp_daily.dropna(axis=0,subset=['month'])
del gdp_daily['month']
del gdp_daily['cal_month']
del gdp_daily['quarter']
gdp_daily['cal_date'] = gdp_daily['cal_date'].apply(lambda x:int(x))
all_daily = pd.merge(gdp_daily,futures,how='left',left_on='cal_date',right_on='trade_date')
all_daily.fillna(method = 'ffill',inplace=True)
all_daily.to_csv('all_features.csv',index=False)